export { default as IPhoneX } from './IPhoneX'
export { default as IPhone8 } from './IPhone8'
export { default as IPad } from './IPad'
export { default as IMac } from './IMac'
export { default as MacbookPro } from './MacbookPro'
